import type { UiLanguage } from "./types";

export const UI_COPY = {
  ENG: {
    generationMode: "GENERATION MODE", editLists: "Edit lists", resetAll: "Reset all", resetPrompt: "Reset the current prompt?", generateCopy: "Generate & copy",
    subject: "Subject", characterSetup: "Character setup", characterDescription: "Adult identity and visual continuity.", adultsOnly: "Adults only. All performers must be consenting adults.",
    ageInputMode: "Age input mode", exact: "Exact", range: "Range", age: "Age", hardMinimum: "Hard minimum: 18", ageFrom: "Age from", ageTo: "Age to",
    bodyType: "Body type", hair: "Hair", eyes: "Eyes", skin: "Skin", includeMaleActor: "Include male actor", build: "Build", ageFeel: "Age feel", faceVisible: "Face visible", globalStyle: "Global style", lighting: "Lighting",
    scene: "Scene", direction: "Direction", directionDescription: "Set the location, wardrobe, and audio bed.", situation: "Situation", customSituation: "Custom situation", customSituationPlaceholder: "Describe a private adult setting", wardrobe: "Wardrobe", startingClothing: "Starting clothing", soundDesign: "Sound design", soundPreset: "Sound preset", customSoundscape: "Custom soundscape", music: "Music", globalNotes: "Global notes", notesHint: "Added at the end of Shot 1.", notesPlaceholder: "Motion, continuity, lens, pacing…",
    sequenceBuilder: "Sequence builder", timeline: "Timeline", timelineDescription: "Arrange physical beats, framing, and emotional progression.", duration: "DURATION", durationControl: "Duration", secondTimeline: "second timeline", sequenceAligned: "Sequence aligned", timingIssues: "timing issues", timingIssue: "timing issue", autoFit: "Auto-fit timing", createFirstEvent: "Create the first event", autoTimed: "Your {duration}-second sequence will be timed automatically.", addEvent: "Add event",
    event: "EVENT", dragEvent: "Drag event", deleteEvent: "Delete event", start: "Start", end: "End", camera: "Camera", clothingState: "Clothing state", position: "Position", action: "Action", expression: "Expression", additionalDirection: "Additional direction", directionPlaceholder: "Body movement, continuity, lens behavior…", existing: "existing",
    liveOutput: "LIVE OUTPUT", structuredPrompt: "H3 structured prompt", chars: "chars", copied: "Copied", copy: "Copy", togglePreview: "Toggle prompt preview", presetName: "Preset name", savePreset: "Save preset", deletePreset: "Delete {name}",
    localMasterData: "LOCAL MASTER DATA", dropdownLibrary: "Dropdown library", masterDescription: "Add, rename, or remove the options used throughout the studio.", closeListEditor: "Close list editor", masterCategories: "Master data categories", filterOptions: "Filter options", addTo: "Add to {category}", addOption: "Add {category} option", add: "Add", editOption: "Edit {value}", deleteOption: "Delete {value}", noMatching: "No matching options.", changesSaved: "Changes are saved automatically on this device.", restoreDefaults: "Restore all defaults", restoreConfirm: "Restore every dropdown list to its original values?",
  },
  JAP: {
    generationMode: "生成モード", editLists: "リスト編集", resetAll: "すべてリセット", resetPrompt: "現在のプロンプトをリセットしますか？", generateCopy: "生成してコピー",
    subject: "人物", characterSetup: "キャラクター設定", characterDescription: "成人の人物設定と映像上の一貫性を調整します。", adultsOnly: "成人のみ。登場人物は全員、合意のある18歳以上の成人です。",
    ageInputMode: "年齢入力モード", exact: "固定", range: "範囲", age: "年齢", hardMinimum: "下限：18歳", ageFrom: "年齢（下限）", ageTo: "年齢（上限）",
    bodyType: "体型", hair: "髪型", eyes: "目元", skin: "肌", includeMaleActor: "男性出演者を含める", build: "体格", ageFeel: "年齢の印象", faceVisible: "顔を表示", globalStyle: "全体スタイル", lighting: "ライティング",
    scene: "シーン", direction: "演出設定", directionDescription: "場所、衣装、音響のベースを設定します。", situation: "状況", customSituation: "状況を自由入力", customSituationPlaceholder: "大人向けのプライベートな場所を入力", wardrobe: "衣装", startingClothing: "開始時の衣装", soundDesign: "音響設計", soundPreset: "サウンドプリセット", customSoundscape: "サウンドを自由入力", music: "音楽", globalNotes: "全体メモ", notesHint: "Shot 1 の末尾に追加されます。", notesPlaceholder: "動き、連続性、レンズ、テンポ…",
    sequenceBuilder: "シーケンス作成", timeline: "タイムライン", timelineDescription: "動き、フレーミング、感情の流れを組み立てます。", duration: "尺", durationControl: "尺", secondTimeline: "秒タイムライン", sequenceAligned: "タイミングは整っています", timingIssues: "件のタイミング問題", timingIssue: "件のタイミング問題", autoFit: "時間を自動調整", createFirstEvent: "最初のイベントを作成", autoTimed: "{duration}秒のシーケンスを自動で配分します。", addEvent: "イベントを追加",
    event: "イベント", dragEvent: "イベントをドラッグ", deleteEvent: "イベントを削除", start: "開始", end: "終了", camera: "カメラ", clothingState: "衣装の状態", position: "体位", action: "アクション", expression: "表情", additionalDirection: "追加演出", directionPlaceholder: "身体の動き、連続性、レンズの挙動…", existing: "既存の値",
    liveOutput: "ライブ出力", structuredPrompt: "H3 構造化プロンプト", chars: "文字", copied: "コピー済み", copy: "コピー", togglePreview: "プロンプトプレビューを切替", presetName: "プリセット名", savePreset: "プリセットを保存", deletePreset: "{name} を削除",
    localMasterData: "ローカルマスターデータ", dropdownLibrary: "プルダウン項目", masterDescription: "スタジオ内で使用する選択肢の追加・名称変更・削除ができます。", closeListEditor: "リスト編集を閉じる", masterCategories: "マスターデータのカテゴリ", filterOptions: "項目を絞り込む", addTo: "{category} に追加", addOption: "{category}の項目を追加", add: "追加", editOption: "{value} を編集", deleteOption: "{value} を削除", noMatching: "一致する項目はありません。", changesSaved: "変更はこの端末へ自動保存されます。", restoreDefaults: "すべて初期値に戻す", restoreConfirm: "すべてのプルダウン項目を初期値へ戻しますか？",
  },
} as const;

export type CopyKey = keyof typeof UI_COPY.ENG;

export const translate = (language: UiLanguage, key: CopyKey, values: Record<string, string | number> = {}) =>
  Object.entries(values).reduce((text, [name, value]) => text.replace(`{${name}}`, String(value)), UI_COPY[language][key]);

const JP_OPTIONS: Record<string, string> = {
  "slender": "細身", "petite adult": "小柄な成人", "glamorous": "グラマラス", "curvy": "曲線的", "soft and plump": "やわらかくふくよか", "athletic": "アスレチック", "slim with wide hips": "細身でヒップが豊か",
  "long straight black hair": "長いストレートの黒髪", "long wavy black hair": "長いウェーブの黒髪", "shoulder-length black hair": "肩までの黒髪", "bob cut black hair": "黒髪のボブ", "long brown hair": "長い茶髪", "ponytail black hair": "黒髪ポニーテール", "messy long black hair": "ラフな長い黒髪", "elegant updo": "上品なアップヘア",
  "large brown eyes": "大きな茶色の瞳", "dark brown eyes": "濃い茶色の瞳", "deep black eyes": "深い黒い瞳", "gentle brown eyes": "やわらかな茶色の瞳",
  "fair Japanese skin with realistic texture": "リアルな質感の明るい日本人の肌", "warm ivory Japanese skin with natural pores": "自然な毛穴感のある温かいアイボリーの日本人の肌", "lightly tanned Japanese skin with a subtle sheen": "ほのかな艶のある軽く日焼けした日本人の肌",
  "love hotel bedroom with soft lighting": "柔らかな照明のラブホテルの寝室", "private apartment bedroom at night": "夜のプライベートなアパートの寝室", "executive office after hours": "営業時間後の役員オフィス", "private spa suite": "プライベートスパスイート", "hot spring private room": "温泉の個室", "bathroom with steam": "湯気のあるバスルーム", "boutique fitting room after closing": "閉店後のブティック試着室", "parked car interior at night": "夜の駐車中の車内", "apartment balcony at night": "夜のアパートのバルコニー", "adult cosplay photoshoot studio": "大人向けコスプレ撮影スタジオ", "private massage room": "プライベートなマッサージルーム", "secluded night garden": "人目のない夜の庭", "traditional Japanese room with tatami": "畳のある和室",
  "tailored white blouse and tight black skirt": "仕立てのよい白ブラウスとタイトな黒スカート", "French maid-inspired adult cosplay outfit": "フレンチメイド風の大人向けコスチューム", "medical-themed adult cosplay outfit": "医療テーマの大人向けコスチューム", "lightly opened kimono or yukata": "軽く開いた着物または浴衣", "tight knit sweater dress": "タイトなニットワンピース", "mini skirt with knee-high socks": "ミニスカートとニーハイソックス", "black lace lingerie": "黒レースのランジェリー", "white lace lingerie": "白レースのランジェリー", "red lace lingerie": "赤レースのランジェリー", "competition swimsuit": "競泳水着", "partially shifted clothing": "ずらした衣服", "fully nude": "全裸", "thigh-high stockings only": "サイハイストッキングのみ",
  "missionary position": "正常位", "cowgirl position": "騎乗位", "reverse cowgirl position": "背面騎乗位", "rear-entry position": "後背位", "standing rear-entry position": "立位後背位", "sitting face-to-face": "座位対面", "spooning position": "スプーニング", "standing embrace while being held": "抱えられた立位の抱擁", "prone position": "うつ伏せ", "legs-raised missionary position": "脚を上げた正常位", "mutual oral position": "相互オーラル", "oral stimulation": "オーラル刺激", "breast stimulation": "胸への刺激", "manual stimulation while kissing": "キスをしながらの手による刺激", "from behind while standing against a wall": "壁に立って寄りかかる後背位",
  "passionate kissing and caressing": "情熱的なキスと愛撫", "slowly undressing and shifting clothes": "ゆっくり脱いだり衣服をずらしたりする", "intimate contact beginning": "親密な接触の始まり", "slow rhythmic movement": "ゆっくりしたリズミカルな動き", "intense rhythmic movement": "激しいリズミカルな動き", "changing position with continuous contact": "触れ合いを保ちながら体位を変える", "approaching climax with trembling": "震えながら絶頂に近づく", "shared climax": "同時の絶頂", "external finish": "体外でのフィニッシュ", "afterglow cuddling and kissing": "余韻の抱擁とキス", "camera slowly pushing in": "カメラがゆっくり寄る", "close-up of intertwined bodies": "絡み合う身体のクローズアップ", "looking at the camera with an intense expression": "強い表情でカメラを見る",
  "slowly undressing and caressing her body": "ゆっくり脱ぎながら身体を愛撫する", "sensual self-touch while reclining": "横たわりながら官能的に自分へ触れる", "slow rhythmic solo movement": "ゆっくりしたソロのリズミカルな動き", "using an adult toy with deliberate movement": "大人向けトイを意図的な動きで使う", "climax with a breathless expression": "息を切らした表情で絶頂に達する", "afterglow while resting on the bed": "ベッドで休む余韻",
  "medium shot": "ミディアムショット", "medium close-up": "ミディアムクローズアップ", "close-up on face": "顔のクローズアップ", "extreme close-up": "極端なクローズアップ", "low angle": "ローアングル", "slight high angle": "ややハイアングル", "side profile": "横顔", "over-the-shoulder": "肩越し", "slow push-in": "ゆっくり寄るショット", "static shot": "固定ショット", "gentle tracking shot": "穏やかな追従ショット",
  "flushed cheeks, slightly open mouth, eyes half-closed": "頬を赤らめ、口を少し開き、半開きの目", "intense pleasure expression with unfocused eyes": "焦点の定まらない目の強い快感表情", "shy but aroused expression": "恥じらいながらも高揚した表情", "looking directly at her partner with affection and desire": "愛情と欲望を込めて相手を見つめる", "biting her lip while breathing heavily": "荒い息をしながら唇を噛む", "moaning with her mouth open": "口を開けて喘ぐ",
  "heavy breathing, intimate movement sounds, soft Japanese moans, rhythmic skin contact, and quiet bed creaking": "荒い息づかい、親密な動きの音、小さな日本語の喘ぎ声、リズミカルな肌の触れ合い、静かなベッドのきしみ", "intense movement sounds, rhythmic skin contact, rising moans and gasps, and low male grunts": "激しい動きの音、リズミカルな肌の触れ合い、高まる喘ぎと息をのむ声、低い男性の息遣い", "soft sensual breathing, gentle fabric movement, and quiet whimpers and moans": "柔らかな官能的な息づかい、穏やかな衣擦れ、静かな吐息と喘ぎ", "heavy breathing and close body movement with minimal vocalization": "荒い息づかいと密着した身体の動き、控えめな声",
  "N/A": "なし", "soft sensual ambient": "柔らかな官能的アンビエント", "slow rhythmic bass": "ゆっくりしたリズミカルなベース", "none": "なし",
  "Photorealistic, highly detailed adult content, realistic Japanese skin texture with natural pores and subtle sweat sheen": "フォトリアルで高精細な成人向け表現。自然な毛穴と繊細な汗の艶があるリアルな日本人の肌", "Photorealistic, soft cinematic treatment, highly detailed, realistic anatomy": "フォトリアルで柔らかな映画調、高精細でリアルな人体表現", "Photorealistic, dramatic cinematic treatment, highly detailed skin and natural movement": "フォトリアルでドラマチックな映画調。高精細な肌と自然な動き",
  "soft warm bedside lighting": "柔らかな暖色のベッドサイド照明", "low-key violet and amber lighting": "低照度の紫と琥珀色の照明", "soft diffused window light": "柔らかな拡散窓光", "dramatic side lighting": "ドラマチックなサイドライト", "warm practical lights with deep shadows": "深い影を伴う暖色の実用照明",
  "lean": "細身", "muscular": "筋肉質", "broad-shouldered": "肩幅が広い", "early 20s adult": "成人の20代前半", "late 20s": "20代後半", "early 30s": "30代前半", "mature 40s": "成熟した40代",
};

export const japaneseOption = (option: string) => JP_OPTIONS[option] ?? "日本語訳は未登録です";
