import type { UiLanguage } from "./types";

export const UI_COPY = {
  ENG: {
    generationMode: "GENERATION MODE", editLists: "Edit lists", resetAll: "Reset all", resetPrompt: "Reset the current prompt?", generateCopy: "Generate & copy",
    subject: "Subject", characterSetup: "Character setup", characterDescription: "Adult identity and visual continuity.", adultsOnly: "Adults only. All performers must be consenting adults.",
    ageInputMode: "Age input mode", exact: "Exact", range: "Range", age: "Age", hardMinimum: "Hard minimum: 18", ageFrom: "Age from", ageTo: "Age to",
    bodyType: "Body type", bustSize: "Bust size", hair: "Hair", eyes: "Eyes", skin: "Skin", includeMaleActor: "Include male actor", build: "Build", ageFeel: "Age feel", faceVisible: "Face visible", globalStyle: "Global style", lighting: "Lighting",
    scene: "Scene", direction: "Direction", directionDescription: "Set the location, wardrobe, and audio bed.", situation: "Situation", customSituation: "Custom situation", customSituationPlaceholder: "Describe a private adult setting", wardrobe: "Wardrobe", startingClothing: "Starting clothing", captureSetup: "Capture setup", cameraDevice: "Camera type", focalLength: "Focal length", subjectDistance: "Subject distance", naturalHandheld: "Natural handheld shake", shakeStyle: "Shake character", soundDesign: "Sound design", soundPreset: "Sound preset", customSoundscape: "Custom soundscape", music: "Music", globalNotes: "Global notes", notesHint: "Added at the end of Shot 1.", notesPlaceholder: "Motion, continuity, lens, pacing…",
    sequenceBuilder: "Sequence builder", timeline: "Timeline", timelineDescription: "Arrange physical beats, framing, and emotional progression.", duration: "DURATION", durationControl: "Duration", secondTimeline: "second timeline", sequenceAligned: "Sequence aligned", timingIssues: "timing issues", timingIssue: "timing issue", autoFit: "Auto-fit timing", createFirstEvent: "Create the first event", autoTimed: "Your {duration}-second sequence will be timed automatically.", addEvent: "Add event",
    event: "EVENT", dragEvent: "Drag event", deleteEvent: "Delete event", start: "Start", end: "End", camera: "Camera", pose: "Subject pose", clothingState: "Clothing state", position: "Position", action: "Action", expression: "Expression", additionalDirection: "Additional direction", directionPlaceholder: "Body movement, continuity, lens behavior…", existing: "existing",
    liveOutput: "LIVE OUTPUT", structuredPrompt: "H3 structured prompt", chars: "chars", copied: "Copied", copy: "Copy", togglePreview: "Toggle prompt preview", presetName: "Preset name", savePreset: "Save preset", deletePreset: "Delete {name}",
    localMasterData: "LOCAL MASTER DATA", dropdownLibrary: "Dropdown library", masterDescription: "Add, rename, or remove the options used throughout the studio.", closeListEditor: "Close list editor", masterCategories: "Master data categories", filterOptions: "Filter options", addTo: "Add to {category}", addOption: "Add {category} option", add: "Add", editOption: "Edit {value}", deleteOption: "Delete {value}", noMatching: "No matching options.", changesSaved: "Changes are saved automatically on this device.", restoreDefaults: "Restore all defaults", restoreConfirm: "Restore every dropdown list to its original values?", masterEnglish: "English prompt text", masterJapanese: "Japanese explanation", englishPlaceholder: "English text used in the prompt", japanesePlaceholder: "Japanese translation shown on hover",
  },
  JAP: {
    generationMode: "生成モード", editLists: "リスト編集", resetAll: "すべてリセット", resetPrompt: "現在のプロンプトをリセットしますか？", generateCopy: "生成してコピー",
    subject: "人物", characterSetup: "キャラクター設定", characterDescription: "成人の人物設定と映像上の一貫性を調整します。", adultsOnly: "成人のみ。登場人物は全員、合意のある18歳以上の成人です。",
    ageInputMode: "年齢入力モード", exact: "固定", range: "範囲", age: "年齢", hardMinimum: "下限：18歳", ageFrom: "年齢（下限）", ageTo: "年齢（上限）",
    bodyType: "体型", bustSize: "胸のサイズ", hair: "髪型", eyes: "目元", skin: "肌", includeMaleActor: "男性出演者を含める", build: "体格", ageFeel: "年齢の印象", faceVisible: "顔を表示", globalStyle: "全体スタイル", lighting: "ライティング",
    scene: "シーン", direction: "演出設定", directionDescription: "場所、衣装、音響のベースを設定します。", situation: "状況", customSituation: "状況を自由入力", customSituationPlaceholder: "大人向けのプライベートな場所を入力", wardrobe: "衣装", startingClothing: "開始時の衣装", captureSetup: "撮影設定", cameraDevice: "カメラの種類", focalLength: "焦点距離", subjectDistance: "被写体との距離", naturalHandheld: "自然な手振れ", shakeStyle: "手振れの特徴", soundDesign: "音響設計", soundPreset: "サウンドプリセット", customSoundscape: "サウンドを自由入力", music: "音楽", globalNotes: "全体メモ", notesHint: "Shot 1 の末尾に追加されます。", notesPlaceholder: "動き、連続性、レンズ、テンポ…",
    sequenceBuilder: "シーケンス作成", timeline: "タイムライン", timelineDescription: "動き、フレーミング、感情の流れを組み立てます。", duration: "尺", durationControl: "尺", secondTimeline: "秒タイムライン", sequenceAligned: "タイミングは整っています", timingIssues: "件のタイミング問題", timingIssue: "件のタイミング問題", autoFit: "時間を自動調整", createFirstEvent: "最初のイベントを作成", autoTimed: "{duration}秒のシーケンスを自動で配分します。", addEvent: "イベントを追加",
    event: "イベント", dragEvent: "イベントをドラッグ", deleteEvent: "イベントを削除", start: "開始", end: "終了", camera: "カメラ", pose: "被写体のポーズ", clothingState: "衣装の状態", position: "体位", action: "アクション", expression: "表情", additionalDirection: "追加演出", directionPlaceholder: "身体の動き、連続性、レンズの挙動…", existing: "既存の値",
    liveOutput: "ライブ出力", structuredPrompt: "H3 構造化プロンプト", chars: "文字", copied: "コピー済み", copy: "コピー", togglePreview: "プロンプトプレビューを切替", presetName: "プリセット名", savePreset: "プリセットを保存", deletePreset: "{name} を削除",
    localMasterData: "ローカルマスターデータ", dropdownLibrary: "プルダウン項目", masterDescription: "スタジオ内で使用する選択肢の追加・名称変更・削除ができます。", closeListEditor: "リスト編集を閉じる", masterCategories: "マスターデータのカテゴリ", filterOptions: "項目を絞り込む", addTo: "{category} に追加", addOption: "{category}の項目を追加", add: "追加", editOption: "{value} を編集", deleteOption: "{value} を削除", noMatching: "一致する項目はありません。", changesSaved: "変更はこの端末へ自動保存されます。", restoreDefaults: "すべて初期値に戻す", restoreConfirm: "すべてのプルダウン項目を初期値へ戻しますか？", masterEnglish: "プロンプト用の英語", masterJapanese: "日本語の説明", englishPlaceholder: "プロンプトで使用する英語を入力", japanesePlaceholder: "ホバー時に表示する日本語訳を入力",
  },
} as const;

export type CopyKey = keyof typeof UI_COPY.ENG;

export const translate = (language: UiLanguage, key: CopyKey, values: Record<string, string | number> = {}) =>
  Object.entries(values).reduce((text, [name, value]) => text.replace(`{${name}}`, String(value)), UI_COPY[language][key]);

const JP_OPTIONS: Record<string, string> = {
  "slender": "細身", "petite adult": "小柄な成人", "glamorous": "グラマラス", "curvy": "曲線的", "soft and plump": "やわらかくふくよか", "athletic": "アスレチック", "slim with wide hips": "細身でヒップが豊か",
  "long straight black hair": "長いストレートの黒髪", "long wavy black hair": "長いウェーブの黒髪", "shoulder-length black hair": "肩までの黒髪", "bob cut black hair": "黒髪のボブ", "long brown hair": "長い茶髪", "ponytail black hair": "黒髪ポニーテール", "messy long black hair": "ラフな長い黒髪", "elegant updo": "上品なアップヘア",
  "large brown eyes": "大きな茶色の瞳", "dark brown eyes": "濃い茶色の瞳", "deep black eyes": "深い黒い瞳", "gentle brown eyes": "やわらかな茶色の瞳",
  "fair Japanese skin with realistic texture": "リアルな質感の明るい日本人の肌", "warm ivory Japanese skin with natural pores": "自然な毛穴感のある温かいアイボリーの日本人の肌", "lightly tanned Japanese skin with a subtle sheen": "ほのかな艶のある軽く日焼けした日本人の肌",
  "love hotel bedroom with soft lighting": "柔らかな照明のラブホテルの寝室", "private apartment bedroom at night": "夜のプライベートなアパートの寝室", "executive office after hours": "営業時間後の役員オフィス", "private spa suite": "プライベートスパスイート", "hot spring private room": "温泉の個室", "bathroom with steam": "湯気のあるバスルーム", "boutique fitting room after closing": "閉店後のブティック試着室", "parked car interior at night": "夜の駐車中の車内", "apartment balcony at night": "夜のアパートのバルコニー", "adult cosplay photoshoot studio": "大人向けコスプレ撮影スタジオ", "private massage room": "プライベートなマッサージルーム", "secluded night garden": "人目のない夜の庭", "traditional Japanese room with tatami": "畳のある和室",
  "tailored white blouse and tight black skirt": "仕立てのよい白ブラウスとタイトな黒スカート", "French maid-inspired adult cosplay outfit": "フレンチメイド風の大人向けコスチューム", "medical-themed adult cosplay outfit": "医療テーマの大人向けコスチューム", "lightly opened kimono or yukata": "軽く開いた着物または浴衣", "tight knit sweater dress": "タイトなニットワンピース", "mini skirt with knee-high socks": "ミニスカートとニーハイソックス", "black lace lingerie": "黒レースのランジェリー", "white lace lingerie": "白レースのランジェリー", "red lace lingerie": "赤レースのランジェリー", "competition swimsuit": "競泳水着", "partially shifted clothing": "ずらした衣服", "fully nude": "全裸", "thigh-high stockings only": "サイハイストッキングのみ",
  "missionary position": "正常位", "cowgirl position": "騎乗位", "reverse cowgirl position": "背面騎乗位", "rear-entry position": "後背位", "standing rear-entry position": "立位後背位", "sitting face-to-face": "座位対面", "spooning position": "スプーニング", "standing embrace while being held": "抱えられた立位の抱擁", "prone position": "うつ伏せ", "legs-raised missionary position": "脚を上げた正常位", "mutual oral position": "相互オーラル", "oral stimulation": "オーラル刺激", "breast stimulation": "胸への刺激", "manual stimulation while kissing": "キスをしながらの手による刺激", "from behind while standing against a wall": "壁に立って寄りかかる後背位",
  "passionate kissing and caressing": "情熱的なキスと愛撫", "slowly undressing and shifting clothes": "ゆっくり脱いだり衣服をずらしたりする", "intimate contact beginning": "親密な接触の始まり", "slow rhythmic movement": "ゆっくりしたリズミカルな動き", "intense rhythmic movement": "激しいリズミカルな動き", "changing position with continuous contact": "触れ合いを保ちながら体位を変える", "approaching climax with trembling": "震えながら絶頂に近づく", "shared climax": "同時の絶頂", "external finish": "体外でのフィニッシュ", "afterglow cuddling and kissing": "余韻の抱擁とキス", "camera slowly pushing in": "カメラがゆっくり寄る", "close-up of intertwined bodies": "絡み合う身体のクローズアップ", "looking at the camera with an intense expression": "強い表情でカメラを見る",
  "both hands firmly supporting the adult woman's hips": "両手で女性の腰をしっかり支える", "both hands kneading the adult woman's breasts with anatomically natural finger placement": "自然な指の配置で両手を使って女性の胸を揉む", "fingertips stimulating the adult woman's nipples while the palms support her breasts": "手のひらで胸を支えながら指先で乳首を刺激する", "one hand kneading her breast while the other hand supports her hip": "片手で胸を揉み、もう片方の手で腰を支える", "one hand stimulating her nipple while the other hand holds her waist": "片手で乳首を刺激し、もう片方の手でウエストを支える", "one hand caressing her chest while the other hand supports her lower back": "片手で胸を愛撫し、もう片方の手で腰を支える", "both hands holding her thighs in a stable and physically plausible grip": "両手で太ももを安定して自然に支える", "one hand interlaced with hers while the other hand caresses her breast": "片手を彼女とつなぎ、もう片方の手で胸を愛撫する",
  "face-to-face embrace between two adult women": "成人女性2人の向かい合った抱擁", "side-by-side scissoring position": "横向きで組み合うシザリング体位", "face-to-face tribadism position": "向かい合うトリバディズム体位", "mutual oral 69 position between two adult women": "成人女性2人の相互オーラル69体位", "one woman kneeling between the reclining woman's thighs": "横たわる女性の太ももの間にもう一人が膝をつく体位", "one woman straddling the other woman's thigh": "一方の女性がもう一人の太ももへ跨る体位", "spooning position with the second woman behind": "2人目の女性が後ろ側になるスプーニング体位", "seated lap embrace between two adult women": "成人女性2人の膝上で向かい合う抱擁", "one woman reclining while the second woman leans over her": "一方が横たわり、もう一人が覆いかぶさる体位", "standing face-to-face against a wall": "壁際で向かい合う立位",
  "the two adult women kiss passionately and caress each other": "成人女性2人が情熱的にキスしながら互いを愛撫する", "they slowly undress each other while maintaining eye contact": "視線を合わせながら互いの衣服をゆっくり脱がせる", "the second woman massages and stimulates the first woman's breasts and nipples": "2人目の女性が1人目の胸と乳首を揉みながら刺激する", "the second woman performs deliberate manual vulva stimulation": "2人目の女性が手で丁寧に外陰部を刺激する", "the second woman performs oral stimulation on the reclining woman": "2人目の女性が横たわる女性へオーラル刺激を行う", "both women perform mutual oral stimulation": "女性2人が相互にオーラル刺激を行う", "the two women perform slow rhythmic tribadism": "女性2人がゆっくりリズミカルなトリバディズムを行う", "the two women perform intense rhythmic scissoring": "女性2人が激しくリズミカルなシザリングを行う", "the second woman uses a selected adult toy on the first woman": "2人目の女性が選択した大人向けトイを1人目へ使用する", "the two women change positions while maintaining continuous intimate contact": "女性2人が密着を保ちながら体位を変える", "both women approach a shared climax with trembling": "女性2人が震えながら同時の絶頂へ近づく", "the two women cuddle and kiss during the afterglow": "女性2人が余韻の中で抱き合いキスする",
  "slowly undressing and caressing her body": "ゆっくり脱ぎながら身体を愛撫する", "sensual self-touch while reclining": "横たわりながら官能的に自分へ触れる", "slow rhythmic solo movement": "ゆっくりしたソロのリズミカルな動き", "using an adult toy with deliberate movement": "大人向けトイを意図的な動きで使う", "climax with a breathless expression": "息を切らした表情で絶頂に達する", "afterglow while resting on the bed": "ベッドで休む余韻",
  "medium shot": "ミディアムショット", "medium close-up": "ミディアムクローズアップ", "close-up on face": "顔のクローズアップ", "extreme close-up": "極端なクローズアップ", "eye-level angle": "目線の高さ", "low angle": "ローアングル", "slight high angle": "ややハイアングル", "side profile": "横顔", "over-the-shoulder": "肩越し", "slow push-in": "ゆっくり寄るショット", "static shot": "固定ショット", "gentle tracking shot": "穏やかな追従ショット",
  "extreme close-up of the face, facial details fill the frame": "顔の細部が画面を満たす極端なクローズアップ", "close-up of the face and shoulders": "顔と肩のクローズアップ", "medium close-up from the chest up": "胸から上のミディアムクローズアップ", "medium shot from the waist up": "腰から上のミディアムショット", "medium full shot from the knees up": "膝から上のミディアムフルショット", "wide shot, full body visible with generous space around the subject": "全身と周囲の余白を広く見せるワイドショット", "wide establishing shot, full body visible with lots of environment": "全身と多くの環境を見せるワイドな状況説明ショット",
  "natural perspective with a balanced relationship between subject and environment": "被写体と環境の関係が均衡した自然な遠近感", "shallow depth of field with a softly blurred background": "背景が柔らかくぼける浅い被写界深度", "background heavily blurred, isolating the subject": "背景を大きくぼかして被写体を分離", "long-lens look, background compressed and appearing close to the subject": "背景が圧縮され被写体の近くに見える望遠風の見え方", "wide-angle look with generous environmental space and mild perspective expansion": "広い環境と緩やかな遠近の強調がある広角風の見え方", "intimate close framing with the face and hands visually dominant": "顔と手を視覚的に強調する親密な近接構図",
  "locked-off static": "完全固定", "pushes in toward the subject": "被写体へプッシュイン", "pulls back from the subject": "被写体からプルバック", "pans left": "左へパン", "pans right": "右へパン", "tracks beside the subject": "被写体の横を追従", "arcs around the subject": "被写体の周囲を円弧移動", "tilts up": "上へチルト", "tilts down": "下へチルト",
  "small amplitude": "小さい振幅", "medium amplitude": "中程度の振幅", "large amplitude": "大きい振幅", "very slow speed": "非常に遅い速度", "slow speed": "遅い速度", "medium speed": "中程度の速度", "fast speed": "速い速度",
  "male performer POV, first-person perspective": "男性出演者の主観（POV／一人称視点）",
  "flushed cheeks, slightly open mouth, eyes half-closed": "頬を赤らめ、口を少し開き、半開きの目", "intense pleasure expression with unfocused eyes": "焦点の定まらない目の強い快感表情", "shy but aroused expression": "恥じらいながらも高揚した表情", "looking directly at her partner with affection and desire": "愛情と欲望を込めて相手を見つめる", "biting her lip while breathing heavily": "荒い息をしながら唇を噛む", "moaning with her mouth open": "口を開けて喘ぐ",
  "openly enthusiastic, actively participating, and clearly enjoying every moment": "積極的に参加し、終始はっきり楽しんでいる", "affectionate and emotionally connected with warm reciprocal reactions": "愛情深く心が通い合い、温かな反応を返す", "playful and teasing with confident eye contact and inviting body language": "自信のある視線と誘うような身振りで、遊び心たっぷりに焦らす", "confident and assertive while directing the pace of the encounter": "自信を持って積極的にペースを主導する", "shy but clearly consenting, gradually becoming more expressive and engaged": "恥じらいながらも明確に同意し、次第に表情豊かで積極的になる", "initially nervous but clearly consenting, relaxing after a reassuring check-in": "最初は緊張しているが明確に同意し、安心確認の後にリラックスする", "intensely submissive within mutually agreed boundaries while remaining responsive": "合意した境界内で強く従属的に演じつつ、相手へ明確に反応する", "consensually dominant, confidently guiding her partner within agreed boundaries": "合意のもとで主導的になり、決めた境界内で自信を持って相手を導く", "emotionally overwhelmed by pleasure while continuing clear affirmative participation": "快感に圧倒されながらも、明確で肯定的な参加を続ける", "quiet and sensual with subtle but unmistakably positive responses": "静かで官能的に、控えめだが明確に肯定的な反応を示す",
  "continuous enthusiastic verbal and physical consent from both adult performers": "成人出演者双方が言葉と身体で継続的かつ積極的に同意を示す", "clear affirmative consent before each escalation in intensity": "強度を上げる前に毎回はっきり肯定の同意を確認する", "the partner checks her comfort and she gives an unmistakably positive confirmation": "相手が快適さを確認し、女性が明確に肯定して応じる", "mutually agreed power-play with established boundaries and a safeword": "境界とセーフワードを事前に決めた双方合意のパワープレイ", "slow escalation only after explicit permission and positive reciprocal movement": "明示的な許可と肯定的な動きの後にのみ、ゆっくり強度を上げる", "either adult performer can pause at any moment and the partner responds immediately": "どちらの成人出演者もいつでも中断でき、相手は直ちに応じる",
  "no visible perspiration": "汗を表示しない", "a subtle natural sweat sheen on her skin": "肌にごく薄い自然な汗の艶", "fine beads of perspiration on her forehead, neck, and upper chest": "額・首・胸元に細かな汗の粒", "moderate realistic perspiration glistening across her face and body": "顔と身体に光る中程度のリアルな汗", "heavy realistic perspiration with visible droplets running naturally along her skin": "肌を自然に流れる目立つ汗の滴",
  "no visible lotion": "ローションを表示しない", "a light transparent lotion sheen on selected areas of her skin": "肌の選択箇所に薄く透明なローションの艶", "a moderate layer of clear glossy lotion spread naturally across her body": "身体へ自然に広がる中程度の透明で艶のあるローション", "a generous coating of clear viscous lotion with realistic highlights and slow movement": "リアルな反射とゆっくりした流れのある多めの透明な粘性ローション", "clear lotion applied mainly to her chest and upper body": "胸と上半身を中心に透明なローションを塗る", "clear lotion applied mainly to her hips, thighs, and lower body": "腰・太もも・下半身を中心に透明なローションを塗る",
  "no visible lactation": "母乳を表示しない", "a subtle small amount of breast milk visible at her nipples": "乳首にごく少量の母乳が見える", "small realistic droplets of breast milk forming at her nipples": "乳首に小さくリアルな母乳の滴ができる", "a moderate natural flow of breast milk from her nipples": "乳首から中程度の自然な母乳が流れる", "visible breast milk tracing naturally down the skin of her chest": "母乳が胸の肌を自然に伝って流れる",
  "heavy breathing, intimate movement sounds, soft Japanese moans, rhythmic skin contact, and quiet bed creaking": "荒い息づかい、親密な動きの音、小さな日本語の喘ぎ声、リズミカルな肌の触れ合い、静かなベッドのきしみ", "intense movement sounds, rhythmic skin contact, rising moans and gasps, and low male grunts": "激しい動きの音、リズミカルな肌の触れ合い、高まる喘ぎと息をのむ声、低い男性の息遣い", "soft sensual breathing, gentle fabric movement, and quiet whimpers and moans": "柔らかな官能的な息づかい、穏やかな衣擦れ、静かな吐息と喘ぎ", "heavy breathing and close body movement with minimal vocalization": "荒い息づかいと密着した身体の動き、控えめな声",
  "N/A": "なし", "soft sensual ambient": "柔らかな官能的アンビエント", "slow rhythmic bass": "ゆっくりしたリズミカルなベース", "none": "なし",
  "Photorealistic, highly detailed adult content, realistic Japanese skin texture with natural pores and subtle sweat sheen": "フォトリアルで高精細な成人向け表現。自然な毛穴と繊細な汗の艶があるリアルな日本人の肌", "Photorealistic, soft cinematic treatment, highly detailed, realistic anatomy": "フォトリアルで柔らかな映画調、高精細でリアルな人体表現", "Photorealistic, dramatic cinematic treatment, highly detailed skin and natural movement": "フォトリアルでドラマチックな映画調。高精細な肌と自然な動き",
  "soft warm bedside lighting": "柔らかな暖色のベッドサイド照明", "low-key violet and amber lighting": "低照度の紫と琥珀色の照明", "soft diffused window light": "柔らかな拡散窓光", "dramatic side lighting": "ドラマチックなサイドライト", "warm practical lights with deep shadows": "深い影を伴う暖色の実用照明",
  "lean": "細身", "muscular": "筋肉質", "broad-shouldered": "肩幅が広い", "early 20s adult": "成人の20代前半", "late 20s": "20代後半", "early 30s": "30代前半", "mature 40s": "成熟した40代",
  "standing in a relaxed pose": "自然にリラックスして立つ", "kneeling upright": "上体を起こして膝立ち", "lying on her back": "仰向けに横たわる", "lying on her side": "横向きに横たわる", "seated with legs crossed": "脚を組んで座る", "leaning forward naturally": "自然に前傾する", "arching her back": "背中を反らす", "hands raised above her head": "両手を頭上に上げる",
  "front-facing toward the camera with shoulders and hips squared to the lens": "肩と腰をレンズへ正対させてカメラ正面を向く", "front-facing toward the camera with a slight natural torso twist": "わずかに自然なひねりを加えてカメラ正面を向く", "three-quarter view toward the camera": "カメラに向けた斜め45度の向き", "facing the camera while the head and eyes look directly into the lens": "身体をカメラへ向け、顔と視線もレンズへ正対する", "facing the partner while keeping the torso open toward the camera": "相手を向きながら上半身はカメラへ開く", "side profile to the camera": "カメラに対して真横を向く", "back facing the camera while looking over her shoulder": "背中をカメラへ向けて肩越しに振り返る",
  "face, shoulders, and chest oriented directly toward the camera": "顔・肩・胸をカメラへ正面向きにする", "head and eyes turned toward the camera while the shoulders follow the selected pose": "肩はポーズに従い、顔と視線だけをカメラへ向ける", "chest open toward the camera in a three-quarter view": "胸をカメラへ開いた斜め45度の向き", "upper body oriented toward the partner": "上半身を相手へ向ける",
  "hips directed away from the camera toward the partner behind her": "腰をカメラと反対側にいる後方の相手へ向ける", "hips squared toward the camera": "腰をカメラへ正対させる", "hips at a three-quarter angle to the camera": "腰をカメラへ斜め45度に向ける", "hips side-on to the camera": "腰をカメラへ真横に向ける", "hips follow the selected pose naturally": "腰の向きは選択したポーズに自然に従う",
  "camera positioned directly in front of the primary woman at her eye level": "メイン女性の正面かつ目線の高さにカメラを配置", "camera positioned directly in front of the primary woman at her eye level while she is on all fours": "四つん這いのメイン女性の正面かつ目線の高さにカメラを配置", "camera positioned at a three-quarter front view of the primary woman": "メイン女性の正面斜め45度にカメラを配置", "camera positioned directly beside the primary woman": "メイン女性の真横にカメラを配置", "camera positioned behind the primary woman": "メイン女性の後方にカメラを配置", "camera positioned over the partner's shoulder toward the primary woman": "相手の肩越しにメイン女性を撮る位置へカメラを配置",
  "consumer camcorder": "家庭用ビデオカメラ", "iPhone camera": "iPhoneカメラ", "professional cinema camera": "プロフェッショナルシネマカメラ", "compact CCD camera": "小型CCDカメラ",
  "18mm ultra-wide": "18mm 超広角", "24mm wide-angle": "24mm 広角", "35mm natural wide": "35mm 自然な広角", "50mm standard": "50mm 標準", "85mm portrait": "85mm ポートレート", "120mm telephoto": "120mm 望遠",
  "0.3m extreme close distance": "被写体から0.3mの極近距離", "0.6m close distance": "被写体から0.6mの近距離", "1.5m medium distance": "被写体から1.5mの中距離", "3m full-body distance": "被写体から3mの全身距離", "5m or more distant view": "被写体から5m以上の遠景",
  "subtle micro-shake": "ごく微細な手振れ", "natural documentary shake": "自然なドキュメンタリー調の手振れ", "pronounced handheld shake": "はっきりした手持ちカメラの揺れ",
  "A-cup breasts": "Aカップ", "B-cup breasts": "Bカップ", "C-cup breasts": "Cカップ", "D-cup breasts": "Dカップ", "E-cup breasts": "Eカップ", "F-cup breasts": "Fカップ", "G-cup breasts": "Gカップ", "H-cup breasts": "Hカップ", "I-cup breasts": "Iカップ",
  "automatically derived from the selected couple position": "選択したカップルの体位から女性の姿勢を自動決定", "seated M-shaped leg-spread pose": "座ったM字開脚", "kneeling with thighs spread apart": "両脚を開いた膝立ち", "reclining with both legs raised": "両脚を上げて横たわる", "lying prone with hips elevated": "腰を高くしたうつ伏せ", "on all fours with an arched back": "背中を反らした四つん這い", "bent forward while supported by a stable surface": "安定した台に支えられて前屈", "standing with one leg raised and supported": "片脚を台に乗せた立ち姿", "deep squat with knees spread apart": "両膝を開いた深いスクワット", "seated on the edge of the bed with legs apart": "ベッドの端で脚を開いて座る", "side-lying with the upper leg raised": "上側の脚を上げた横向き", "standing against a wall with arms raised": "両腕を上げて壁に立つ", "facing away while looking back over her shoulder": "背を向けて肩越しに振り返る", "kneeling while sitting back on her heels": "かかとに腰を下ろした正座姿勢", "reclining with knees drawn toward her chest": "膝を胸へ引き寄せて横たわる",
  "no adult toy": "大人向けトイなし", "small handheld vibrator": "小型ハンドバイブ", "full-size wand vibrator": "大型ワンドバイブ", "smooth insertable dildo": "滑らかな挿入用ディルド", "suction-cup mounted dildo fixed securely to a stable surface": "安定した面へ固定する吸盤式ディルド", "remote-controlled wearable vibrator": "遠隔操作式ウェアラブルバイブ", "compact thrusting machine with a secured dildo attachment": "ディルドを固定した小型ピストンマシン",
  "f/1.4": "f/1.4（非常に明るい）", "f/2": "f/2（明るい）", "f/2.8": "f/2.8", "f/4": "f/4", "f/5.6": "f/5.6", "f/8": "f/8", "f/11": "f/11（深いピント）",
  "very shallow depth of field": "非常に浅い被写界深度", "shallow depth of field": "浅い被写界深度", "moderate depth of field": "中程度の被写界深度", "deep depth of field": "深い被写界深度",
  "eyes": "目", "face": "顔", "hands": "手", "upper body": "上半身", "full body": "全身", "nearest subject": "最も近い被写体", "background detail": "背景の細部",
  "locked manual focus": "固定マニュアルフォーカス", "continuous subject-tracking autofocus": "被写体追従オートフォーカス", "natural rack focus": "自然なラックフォーカス", "subtle focus breathing": "微細なフォーカスブリージング", "brief realistic focus hunting": "短く自然なピント迷い",
  "24 fps cinematic motion": "24fpsの映画的な動き", "30 fps natural video motion": "30fpsの自然な映像", "60 fps crisp fluid motion": "60fpsの滑らかで鮮明な動き",
  "90-degree shutter": "90度シャッター", "180-degree shutter": "180度シャッター", "270-degree shutter": "270度シャッター", "360-degree shutter": "360度シャッター",
  "continuous cut-free movement": "カットなしの連続移動", "hard cut": "ハードカット", "match cut": "マッチカット", "soft dissolve": "ソフトディゾルブ", "whip-pan transition": "ウィップパン・トランジション",
};

export const japaneseOption = (option: string) => JP_OPTIONS[option] ?? "日本語訳は未登録です";
